### PR TITLE
Fixes #35 - FrozenError: can't modify frozen String

### LINKED ISSUE #35: FrozenError: can't modify frozen String: "UpdateImportCount"
### FrozenError: can't modify frozen String: "UpdateImportCount"
||version|
|-|-|
| Ruby |2.7.0  |
|Rails |5.2.4.2|

```
     FrozenError:
       can't modify frozen String: "UpdateImportCount"
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/redis-mutex-4.0.1/lib/redis_mutex/macro.rb:41:in `block in method_added'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:301:in `execute_job'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:296:in `block in process_job'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/middleware/chain.rb:133:in `invoke'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:295:in `process_job'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:89:in `block in raw_push'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:85:in `each'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/testing.rb:85:in `raw_push'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-pro-5.0.0/lib/sidekiq/batch/client.rb:40:in `raw_push'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/client.rb:74:in `push'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/worker.rb:149:in `client_push'
     # /home/deepak/.rvm/gems/ruby-2.7.0@api/gems/sidekiq-5.2.8/lib/sidekiq/worker.rb:93:in `perform_async'
     # ./app/interactors/ingester/file_processor.rb:139:in `send_messages'
```

### PR DESCRIPTION
**Pull request by deepakmahakale**
Fixes #35 - FrozenError: can't modify frozen String

### CODE REVIEW

**Comment by kenn** [comment]
In what case does that happen?

**Comment by deepakmahakale** [comment]
It happens when you are using ruby 2.7 the class name is a frozen string 

and when we do the following:
```ruby
self.class.name << '#'
```
we are trying to append to the same string 

so either interpolation or `dup` needs to be done

**Comment by kenn** [comment]
Should be fixed with #34 let me know if not!

**Comment by deepakmahakale** [comment]
@kenn Yes, It should be fixed with #34 :+1:

**Pull request closed without merging**
